# Generated by Django 6.0.7 on 2026-07-23 08:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Millilitres'), ('l', 'Litres'), ('pcs', 'Pieces')], default='g', max_length=5)),
                ('current_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current quantity on hand, in the unit above.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reorder_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="When current_stock drops to/below this, it's considered low stock.", max_digits=10)),
                ('supplier_contact', models.CharField(blank=True, help_text='Phone number or name of the supplier to contact for reorders.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=3, help_text="How much of this ingredient (in the ingredient's unit) one unit of the menu item consumes.", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='billing.ingredient')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_lines', to='billing.menuitem')),
            ],
            options={
                'ordering': ['menu_item__name', 'ingredient__name'],
                'unique_together': {('menu_item', 'ingredient')},
            },
        ),
    ]
