# Generated by Django 6.0.7 on 2026-07-23 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_ingredient_recipemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(help_text='The date this prediction is FOR.')),
                ('predicted_quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Filled in after forecast_date passes — actual units sold. Used by the Phase 5 anomaly agent.', max_digits=8, null=True)),
                ('model_version', models.CharField(blank=True, help_text='Tag for which trained model produced this, e.g. a timestamp or git hash.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='billing.menuitem')),
            ],
            options={
                'ordering': ['-forecast_date', 'menu_item__name'],
                'unique_together': {('menu_item', 'forecast_date')},
            },
        ),
    ]
