# Generated by Django 6.0.7 on 2026-07-23 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_demandforecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(help_text="The date this agent run was for (usually 'today', deciding for tomorrow's demand).")),
                ('decision', models.CharField(choices=[('sufficient', 'Sufficient stock — no action needed'), ('low_stock', 'Low stock — reorder message drafted'), ('critical', 'Critical — reorder message sent immediately')], max_length=20)),
                ('action_taken', models.CharField(choices=[('none', 'No action'), ('logged_only', 'Logged only'), ('message_drafted', 'Message drafted (not sent)'), ('message_sent', 'Message sent to supplier')], default='none', max_length=20)),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predicted_demand', models.DecimalField(decimal_places=2, help_text='Total forecasted consumption of this ingredient for the forecast date.', max_digits=10)),
                ('projected_stock_after_demand', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suggested_order_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reasoning', models.TextField(help_text='Plain-English explanation of why the agent decided what it decided.')),
                ('message_draft', models.TextField(blank=True, help_text='The supplier reorder message, if one was drafted/sent.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_logs', to='billing.ingredient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]

