# Generated by Django 6.0.7 on 2026-07-25 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_agentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySummaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('summary_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='DemandAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actual_quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('variance', models.DecimalField(decimal_places=2, help_text='actual - predicted', max_digits=8)),
                ('variance_pct', models.DecimalField(decimal_places=2, help_text='variance as a % of predicted', max_digits=6)),
                ('flag', models.CharField(choices=[('normal', 'Normal — within expected variance'), ('over_forecast', 'Over-forecast — wastage risk'), ('under_forecast', 'Under-forecast — lost sales risk')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='billing.menuitem')),
            ],
            options={
                'ordering': ['-forecast_date', 'menu_item__name'],
                'unique_together': {('menu_item', 'forecast_date')},
            },
        ),
    ]
