# Generated by Django 6.0.7 on 2026-07-26 06:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_weeklysummaryreport_demandanomaly'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'GPay / UPI'), ('other', 'Other')], default='cash', help_text='How the customer paid — used for the end-of-day cash/UPI audit split.', max_length=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='e.g. 5.00 for 5% tax. Leave 0 to skip tax entirely.', max_digits=4),
        ),
    ]
