# Generated by Django 6.0.7 on 2026-07-27 10:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_bill_payment_method_alter_bill_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='daily_number',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text="A clean, human-friendly order number that resets to 1 each day (e.g. 'Order 3') — separate from the database id.", null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Optional. What it costs you to make one unit — only used later for margin/wastage analysis, never required for billing. Leave 0 if you don't track this.", max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
