# Generated by Django 6.0.7 on 2026-07-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_order_daily_number_alter_menuitem_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentlog',
            name='message_channel',
            field=models.CharField(choices=[('none', 'None'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='none', help_text='Which channel the message was (or would be) sent through.', max_length=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='supplier_whatsapp',
            field=models.CharField(blank=True, help_text="Supplier's WhatsApp number in E.164 format, e.g. +919876543210. Used by the reorder agent to send messages directly.", max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='supplier_contact',
            field=models.CharField(blank=True, help_text="Supplier's name or general contact info.", max_length=100),
        ),
    ]
