# Generated by Django 6.0.7 on 2026-07-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_agentlog_message_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='supports_cheese_option',
            field=models.BooleanField(default=False, help_text="Show an 'Add cheese? +₹20' choice when adding this item (e.g. for burgers)."),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='supports_fried_option',
            field=models.BooleanField(default=False, help_text="Show a 'Fried? +₹20' choice when adding this item (e.g. for momos)."),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='has_extra_cheese',
            field=models.BooleanField(default=False, help_text='Extra cheese — adds ₹20.00 per unit (only meaningful if the menu item supports it).'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_fried',
            field=models.BooleanField(default=False, help_text='Fried option — adds ₹20.00 per unit (only meaningful if the menu item supports it).'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_parcel',
            field=models.BooleanField(default=False, help_text='Takeaway/parcel — adds ₹5.00 per unit.'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('burger', 'Burgers'), ('momo', 'Momos'), ('home_made', 'Home Made'), ('roll', 'Rolls'), ('veg', 'Veg'), ('non_veg', 'Non Veg'), ('pasta', 'Pasta'), ('seafood', 'Seafood'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text="Snapshot of MenuItem.price + any modifier surcharges at the time of order, so later price changes don't rewrite history.", max_digits=8),
        ),
    ]
