# Generated by Django 5.2.16 on 2026-08-04 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_backfill_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentlog',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_logs', to='billing.shop'),
        ),
        migrations.AlterField(
            model_name='demandanomaly',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='billing.shop'),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='billing.shop'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='billing.shop'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='billing.shop'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='billing.shop'),
        ),
        migrations.AlterField(
            model_name='weeklysummaryreport',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to='billing.shop'),
        ),
    ]
