"""
Django settings for tasty_ops project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-78ar06r+zinrt7u^$rq8&=oadynoy7$3!zua2n%&r56^%w+(6k')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])

# Render (and most cloud hosts) terminate HTTPS at a proxy and forward to
# your app as plain HTTP — without this, Django thinks every request is
# insecure, which breaks CSRF checks on every POST (login, logout, forms).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Needed alongside ALLOWED_HOSTS for CSRF to trust your live https:// domain.
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS', default='',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_celery_beat',
    'billing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tasty_ops.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tasty_ops.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Uses PostgreSQL by default. If you don't have Postgres set up yet and just
# want to try the API immediately, set USE_SQLITE=True in your .env file.
# In production (e.g. Render, Railway), a DATABASE_URL env var is provided
# automatically by the Postgres addon and takes priority over everything else.
if config('DATABASE_URL', default=''):
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600, ssl_require=not DEBUG)
    }
elif config('USE_SQLITE', default=False, cast=bool):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='tasty_ops'),
            'USER': config('DB_USER', default='postgres'),
            'PASSWORD': config('DB_PASSWORD', default='postgres'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Celery — scheduled agent runs (forecast every evening, reorder agent right after).
# Requires Redis running locally (redis-cli ping should return PONG).
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Schedule is also editable at runtime via Django admin ("Periodic tasks",
# thanks to django_celery_beat) — these are just the defaults on first run.
# crontab(hour=21, minute=0) means "every day at 21:00", in CELERY_TIMEZONE.
from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    'nightly-demand-forecast': {
        'task': 'billing.tasks.run_nightly_forecast',
        'schedule': crontab(
            hour=config('FORECAST_HOUR', default=21, cast=int),
            minute=config('FORECAST_MINUTE', default=0, cast=int),
        ),
        'options': {'expires': 3600},
    },
    'nightly-reorder-agent': {
        'task': 'billing.tasks.run_nightly_reorder_agent',
        'schedule': crontab(
            hour=config('REORDER_AGENT_HOUR', default=21, cast=int),
            minute=config('REORDER_AGENT_MINUTE', default=15, cast=int),
        ),
        'options': {'expires': 3600},
    },
    'nightly-anomaly-check': {
        'task': 'billing.tasks.run_nightly_anomaly_check',
        'schedule': crontab(
            hour=config('ANOMALY_CHECK_HOUR', default=23, cast=int),
            minute=config('ANOMALY_CHECK_MINUTE', default=0, cast=int),
        ),
        'options': {'expires': 3600},
    },
    'weekly-summary-report': {
        'task': 'billing.tasks.run_weekly_summary_report',
        'schedule': crontab(
            hour=config('WEEKLY_SUMMARY_HOUR', default=8, cast=int),
            minute=config('WEEKLY_SUMMARY_MINUTE', default=0, cast=int),
            day_of_week=config('WEEKLY_SUMMARY_DAY', default=1, cast=int),  # 1 = Monday
        ),
        'options': {'expires': 3600},
    },
}

# Email — used by the reorder agent to message suppliers. Console backend
# (default) just prints the "sent" email to your terminal, so you can see
# it working without setting up real SMTP. Point this at a real SMTP
# provider whenever you're ready to actually message suppliers.
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='tastyzone@example.com')

# Twilio WhatsApp — primary channel for supplier reorder messages.
# Leave blank to skip WhatsApp entirely; the agent falls back to email.
# Get a free sandbox number at https://console.twilio.com (Messaging > Try WhatsApp).
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_WHATSAPP_FROM = config('TWILIO_WHATSAPP_FROM', default='')  # e.g. +14155238886 (Twilio sandbox number)